
server:
  port: 8051

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: GESTION-TACHES
          uri: http://localhost:8890
          predicates:
            - Path=/tache/**
        - id: GESTION-PROJET
          uri: http://localhost:8898
          predicates:
            - Path=/projet/**
        - id: gestion_conges
          uri: http://localhost:8074
          predicates:
            - Path=/conge/**
        - id: gestion_stage
          uri: http://localhost:2020
          predicates:
            - Path=/stage/**
        - id: complaint-s
          uri: http://localhost:8030
          predicates:
            - Path=/complaint/**
        - id: EMP.EventShare.Api
          uri: http://localhost:5179
          predicates:
            - Path=/api/Event/**



